
# A string used as a secret to generate JWT tokens 
project_id = "ukrehtjivmsjroreoosr"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = false
port = 54327
vector_port = 54328

[realtime]
enabled = true

# Used by the Edge Functions feature when running locally
[edge_functions]
enabled = true

[functions.get_entity_type_enum_values]
verify_jwt = true
